//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlterStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ServiceId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Amount { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
